create table "public"."attempts" (
    "id" bigint generated by default as identity not null,
    "uid" uuid not null,
    "pid" bigint not null,
    "start_time" timestamp with time zone not null,
    "jsonb" jsonb not null,
    "has_cheated" boolean
);


alter table "public"."attempts" enable row level security;

create table "public"."puzzles" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone default now(),
    "live_date" date not null,
    "jsonb" jsonb not null,
    "difficulty" text not null default 'daily'::text
);


alter table "public"."puzzles" enable row level security;

create table "public"."solves" (
    "id" bigint generated by default as identity not null,
    "uid" uuid not null,
    "bid" bigint not null,
    "start_time" timestamp with time zone not null,
    "end_time" timestamp with time zone not null,
    "did_cheat" boolean not null
);


alter table "public"."solves" enable row level security;

CREATE UNIQUE INDEX attempts_pkey ON public.attempts USING btree (id);

CREATE UNIQUE INDEX puzzles_id_key ON public.puzzles USING btree (id);

CREATE UNIQUE INDEX puzzles_pkey ON public.puzzles USING btree (id);

CREATE UNIQUE INDEX solves_pkey ON public.solves USING btree (id);

alter table "public"."attempts" add constraint "attempts_pkey" PRIMARY KEY using index "attempts_pkey";

alter table "public"."puzzles" add constraint "puzzles_pkey" PRIMARY KEY using index "puzzles_pkey";

alter table "public"."solves" add constraint "solves_pkey" PRIMARY KEY using index "solves_pkey";

alter table "public"."attempts" add constraint "attempts_pid_fkey" FOREIGN KEY (pid) REFERENCES puzzles(id) not valid;

alter table "public"."attempts" validate constraint "attempts_pid_fkey";

alter table "public"."attempts" add constraint "attempts_uid_fkey" FOREIGN KEY (uid) REFERENCES auth.users(id) not valid;

alter table "public"."attempts" validate constraint "attempts_uid_fkey";

alter table "public"."puzzles" add constraint "puzzles_id_key" UNIQUE using index "puzzles_id_key";

alter table "public"."solves" add constraint "solves_bid_fkey" FOREIGN KEY (bid) REFERENCES puzzles(id) not valid;

alter table "public"."solves" validate constraint "solves_bid_fkey";

alter table "public"."solves" add constraint "solves_uid_fkey" FOREIGN KEY (uid) REFERENCES auth.users(id) not valid;

alter table "public"."solves" validate constraint "solves_uid_fkey";


